Update maven-snapshot-deploy.yaml

diff --git a/.github/workflows/maven-snapshot-deploy.yaml b/.github/workflows/maven-snapshot-deploy.yaml
--- a/.github/workflows/maven-snapshot-deploy.yaml
+++ b/.github/workflows/maven-snapshot-deploy.yaml
@@ -22,7 +22,19 @@ jobs:
     steps:
       - name: "Checkout code"
         uses: actions/checkout@v4
-      - name: Set up JDK
+      - name: "Setup xmlstarlet"
+        run: |
+          sudo apt install -y xmlstarlet
+      - name: "Check that version is SNAPSHOT"
+        run: |
+          IS_SNAPSHOT=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml)
+          if [ "${IS_SNAPSHOT}" == "" ]
+          then
+            echo "❗ The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix." >> $GITHUB_STEP_SUMMARY
+            echo "Workflow fail. Please add '-SNAPSHOT' to the revision."
+            exit 1
+          fi
+      - name: "Set up JDK"
         uses: actions/setup-java@v4
         with:
           java-version: "21"
@@ -37,9 +49,7 @@ jobs:
         run: cat ~/.m2/settings.xml
       - name: "Disable Maven Central Deploy"
         run: |
-          sudo apt install -y xmlstarlet
           xmlstarlet ed -L -d "/_:project/_:build/_:plugins/_:plugin[./_:artifactId='central-publishing-maven-plugin']" ./pom.xml
-          cat ./pom.xml
 
       - name: "Maven deploy"
         run: |
