Update maven-snapshot-deploy.yaml

diff --git a/.github/workflows/maven-snapshot-deploy.yaml b/.github/workflows/maven-snapshot-deploy.yaml
--- a/.github/workflows/maven-snapshot-deploy.yaml
+++ b/.github/workflows/maven-snapshot-deploy.yaml
@@ -29,19 +29,18 @@ jobs:
         shell: bash
         run: |
           cd ${GITHUB_WORKSPACE}
-          # xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml
-          # IS_SNAPSHOT=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml)
-          # if [[ "${IS_SNAPSHOT}" == "" ]]
-          # then
-          #   echo "The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix." >> $GITHUB_STEP_SUMMARY
-          #   echo "Workflow fail. Please add '-SNAPSHOT' to the revision." >> $GITHUB_STEP_SUMMARY
-          #   echo "The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix."
-          #   echo "Workflow fail. Please add '-SNAPSHOT' to the revision."
-          #   exit 1
-          # else
-          #   echo "The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}" >> $GITHUB_STEP_SUMMARY
-          #   echo "The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}"
-          # fi
+          IS_SNAPSHOT=$(xmlstarlet sel -N x="http://maven.apache.org/POM/4.0.0" -t -v "/x:project/x:properties/x:revision[contains(., '-SNAPSHOT')]" ./pom.xml || echo "")
+          if [[ "${IS_SNAPSHOT}" == "" ]]
+          then
+            echo "❗ The project/properties/revision in the pom.xml has no '-SNAPSHOT' postfix." >> $GITHUB_STEP_SUMMARY
+            echo "❗ Workflow fail. Please add '-SNAPSHOT' to the revision." >> $GITHUB_STEP_SUMMARY
+            echo "❗ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix."
+            echo "Workflow fail. Please add '-SNAPSHOT' to the revision."
+            exit 1
+          else
+            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}" >> $GITHUB_STEP_SUMMARY
+            echo "✅ The project/properties/revision in the pom.xml has '-SNAPSHOT' postfix: ${IS_SNAPSHOT}"
+          fi
       - name: "Set up JDK"
         uses: actions/setup-java@v4
         with:
